# yaml-language-server: $schema=https://raw.githubusercontent.com/StrayDragon/llman/main/artifacts/schema/configs/en/llmanspec-config.schema.json
schema: spec-driven
locale: zh-Hans
extra_skills:
- llman-sdd-ff
- llman-sdd-arch-review
- llman-sdd-wayfinder
- llman-sdd-research
